# Generated by Django 5.0.1 on 2024-01-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Course title')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Course preview')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Lesson title')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Lesson preview')),
                ('link', models.CharField(max_length=64, verbose_name='Lesson link')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
