# Generated by Django 5.0.1 on 2024-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscritpion',
            field=models.BooleanField(default=False, verbose_name='Subscribed?'),
        ),
    ]
