# Generated by Django 5.0.1 on 2024-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
    ]
